payum:
    storages:
        Payum\Core\Model\Payment:
            filesystem:
                storage_dir: '%kernel.project_dir%/var/payum/payments'
                id_property: number

    security:
        token_storage:
            Payum\Core\Model\Token:
                filesystem:
                    storage_dir: '%kernel.project_dir%/var/payum/gateways'
                    id_property: hash

    gateways:
        paypal:
            factory: paypal_express_checkout
            username:  'your_paypal_username'
            password:  'your_paypal_password'
            signature: 'your_paypal_signature'
            sandbox: true